name: Upload Videos to YouTube

on:
  push:
    branches:
      - main

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Set up Google Drive and YouTube credentials
      run: |
        echo "GOOGLE_DRIVE_CREDENTIALS=${{ secrets.GOOGLE_DRIVE_CREDENTIALS }}" >> $GITHUB_ENV
        echo "CLIENT_SECRETS_JSON=${{ secrets.CLIENT_SECRETS_JSON }}" >> $GITHUB_ENV

    - name: Run upload script
      run: python upload_videos.py
